### ISSUE TITLE
Scan process stuck at x%

### ISSUE THREAD

**Issue by tseroo** [ioBroker/ioBroker.discovery#108]
Running discovery with version 2.3.1 the scan phase is not finishing at all. At some point between 91 and 98% it is stuck and nothing is happening anymore. Also the last search time is never updated:

![image](https://user-images.githubusercontent.com/10330889/79629351-65e00f80-8149-11ea-8c40-75a2d47129a7.png)

In the log I can see the following entries:
discovery.0 | 2020-04-18 07:48:31.138 | info | (9936) starting. Version 2.3.1 in /opt/iobroker/node_modules/iobroker.discovery, node: v10.19.0
-- | -- | -- | --
host.iobroker | 2020-04-18 07:48:29.694 | info | instance system.adapter.discovery.0 started with pid 9936
host.iobroker | 2020-04-18 07:47:59.661 | info | Restart adapter system.adapter.discovery.0 because enabled
host.iobroker | 2020-04-18 07:47:59.661 | info | instance system.adapter.discovery.0 terminated with code 0 (NO_ERROR)
host.iobroker | 2020-04-18 07:47:59.660 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:68:7)
host.iobroker | 2020-04-18 07:47:59.660 | error | Caught by controller[0]: at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
host.iobroker | 2020-04-18 07:47:59.660 | error | Caught by controller[0]: at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.iobroker | 2020-04-18 07:47:59.660 | error | Caught by controller[0]: at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:71697)
host.iobroker | 2020-04-18 07:47:59.660 | error | Caught by controller[0]: at objects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2491:65)
host.iobroker | 2020-04-18 07:47:59.660 | error | Caught by controller[0]: at adapter.getForeignObject (/opt/iobroker/node_modules/iobroker.discovery/main.js:388:13)
host.iobroker | 2020-04-18 07:47:59.660 | error | Caught by controller[0]: at enumAdapters (/opt/iobroker/node_modules/iobroker.discovery/main.js:70:35)
host.iobroker | 2020-04-18 07:47:59.659 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.iobroker | 2020-04-18 07:47:59.659 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.iobroker | 2020-04-18 07:47:59.659 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.iobroker | 2020-04-18 07:47:59.659 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.iobroker | 2020-04-18 07:47:59.659 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.iobroker | 2020-04-18 07:47:59.658 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.iobroker | 2020-04-18 07:47:59.658 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:723:23)
host.iobroker | 2020-04-18 07:47:59.658 | error | Caught by controller[0]: SyntaxError: Unexpected token throw
host.iobroker | 2020-04-18 07:47:59.658 | error | Caught by controller[0]: ^^^^^
host.iobroker | 2020-04-18 07:47:59.657 | error | Caught by controller[0]: server.send(Buffer.from(request), 0, request.length, 3671, ip, (err, bytes) => err && throw err);
host.iobroker | 2020-04-18 07:47:59.656 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.discovery/lib/adapters/knx.js:47
discovery.0 | 2020-04-18 07:47:59.117 | info | (9664) Terminated (NO_ERROR): Without reason
discovery.0 | 2020-04-18 07:47:59.115 | info | (9664) terminating
discovery.0 | 2020-04-18 07:47:58.607 | error | (9664) /opt/iobroker/node_modules/iobroker.discovery/lib/adapters/knx.js:47 server.send(Buffer.from(request), 0, request.length, 3671, ip, (err, bytes) => err && throw err);
discovery.0 | 2020-04-18 07:47:58.606 | error | (9664) uncaught exception: Unexpected token throw
discovery.0 | 2020-04-18 07:47:58.356 | info | (9664) Found 47 addresses
discovery.0 | 2020-04-18 07:47:58.245 | info | (9664) Done discovering upnp devices. 70 packages received
discovery.0 | 2020-04-18 07:47:58.164 | info | (9664) Done discovering mdns devices. 14 packages received
discovery.0 | 2020-04-18 07:47:57.918 | info | (9664) Done discovering ping devices. 34 packages received
discovery.0 | 2020-04-18 07:47:48.181 | info | (9664) Done discovering udp devices. 1 packages received
discovery.0 | 2020-04-18 07:47:43.244 | info | (9664) Discovering UPnP devices...
discovery.0 | 2020-04-18 07:47:43.165 | info | (9664) Discovering ping devices...
discovery.0 | 2020-04-18 07:47:43.160 | info | (9664) Discovering mDNS devices...
discovery.0 | 2020-04-18 07:42:27.788 | info | (9664) starting. Version 2.3.1 in /opt/iobroker/node_modules/iobroker.discovery, node: v10.19.0
host.iobroker | 2020-04-18 07:42:26.428 | info | instance system.adapter.discovery.0 started with pid 9664

**Comment by Apollon77** [comment]
Please retry with 2.3.2 (GitHub now, latest later)

**Comment by tseroo** [comment]
Working fine! Scan finishes and no errors in log. Great! Thanks!

Only one 'issue' ... my Denon AVR is found but listed > 100 times always
with identical content, not sure why:
[image: image.png]

Am Sa., 18. Apr. 2020 um 10:25 Uhr schrieb Ingo Fischer <
notifications@github.com>:

**Comment by Apollon77** [comment]
I will check later.

**Comment by Apollon77** [comment]
Very intersting. Can you please let it run in debug mode and post the log?

**Comment by tseroo** [comment]
Sure, here is the debug log .. [discovery-debug.log](https://github.com/ioBroker/ioBroker.discovery/files/4498458/discovery-debug.log)

**Comment by Apollon77** [comment]
please check again with 2.3.5
