### ISSUE TITLE
can't update with js-controller 3.2.6-0

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.discovery#125]
in Admin this popup:
![grafik](https://user-images.githubusercontent.com/36229898/104271087-3ffa5800-549a-11eb-8333-b96f7416eb11.png)

![grafik](https://user-images.githubusercontent.com/36229898/104271115-56081880-549a-11eb-8018-592c21d56c64.png)

**Comment by Ilovegym66** [comment]
Admin 4.2.0

**Comment by Apollon77** [comment]
wrong version check in admin, new admin version will come later
