### ISSUE TITLE
G-Homa plug detected as wifilight

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.discovery#136]
**Describe the bug**  
The G-Homa plug is detected as wifilight during the discovery process.

**To Reproduce**  
1. connect G-Homa plug to wifi
2. start discovery process

**Expected behavior**  
Discovery should show G-Homa Adapter instead wifilight.

**Versions:**  
 N/A - issue was reported by a user

**Comment by Apollon77** [comment]
According to Wifilight detection code:

    // We want to support both legacy v5 Bridges (detected by Wifi-Mi-Light)
    // And v6 bridges (detected by HF-LPB100)

and g-home also is discovered as "_hf_lpb100" ... So whats right from wregard to wifilight ?
