### ISSUE TITLE
Error State type: phase1/2/3Voltage & phase1/2/3Power 

### ISSUE THREAD

**Issue by neumeier-cloud** [ioBroker/ioBroker.discovery#148]
ioBroker Logfile Snap
<html>
<body>

discovergy.0 | 2021-05-07 15:05:54.757 | error | (1030) State type : phase3Voltage unknown, send this information to the developer ==> phase3Voltage : 235800
-- | -- | -- | --
discovergy.0 | 2021-05-07 15:05:54.757 | error | (1030) State type : phase2Voltage unknown, send this information to the developer ==> phase2Voltage : 234400
discovergy.0 | 2021-05-07 15:05:54.757 | error | (1030) State type : phase1Voltage unknown, send this information to the developer ==> phase1Voltage : 235400
discovergy.0 | 2021-05-07 15:05:54.757 | error | (1030) State type : phase3Power unknown, send this information to the developer ==> phase3Power : -283540
discovergy.0 | 2021-05-07 15:05:54.757 | error | (1030) State type : phase1Power unknown, send this information to the developer ==> phase1Power : 630210
discovergy.0 | 2021-05-07 15:05:54.757 | error | (1030) State type : phase2Power unknown, send this information to the developer ==> phase2Power : 166830

</body>
</html>

**Comment by Apollon77** [comment]
Hihi ... please check adaptername ... discoverGy :-)
