### ISSUE TITLE
mDNS cannot be compiled on default linux and windows

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.discovery#16]
discovery uses mDNS module and it must be compiled. But discovery is used by the first installation and users get many errors. It can scary for the first time.

How we can solve this? Is there any some npm silence mode? Or may special discovery version by the first time?

**Comment by Apollon77** [comment]
Yes also in Forum many people have problems with this becase starting wirh node 6 it throws error also with other adapter installs ...

**Comment by Apollon77** [comment]
I found mdns-js which is a "Pure Javascript" alternative .... mabe use that for discovering instead of the native comiled one?

**Comment by frankjoke** [comment]
I can look into that, have been writing js-only code for radar, this should add also the possibility to receive the mac addresses and mac vendors of the devices. In this way I can add also discovery of some of my adapters like broadlink2, km200 or xs1. I just tried it for first time and aside the homematic and fritzbox nothing was really found. Also support for BT should be added, which means that adapters which support BT devices should be proposed if BT is available (at lease I can add that for linux).
I will try to work on it until I understood the current structure of the adapter as part of my intention to get some of my adapters listed as well :).
