### ISSUE TITLE
SyntaxError: Missing initializer in const declaration

### ISSUE THREAD

**Issue by Sneak-L8** [ioBroker/ioBroker.discovery#162]
**Describe the bug**  
When opening setting of discovery adapter the following error is reported:
```
discovery.0 2021-06-08 19:32:16.457 warn SyntaxError: Missing initializer in const declaration
discovery.0 2021-06-08 19:32:16.457 warn ^^^^^^^^^^^^^^^^
discovery.0 2021-06-08 19:32:16.457 warn const systemDictionary;
discovery.0 2021-06-08 19:32:16.457 warn (5247) /opt/iobroker/node_modules/iobroker.discovery/admin/words.js:6
```

**To Reproduce**  
Latest verison of adapter from git
Open settings in instance tab.
Error is printed in log and settings screen is almost empty.

**Expected behavior**  
Correct settings display.

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 2.6.3
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: linux

**Additional context**  
Just tried to add discovery for Keba KeContact P30 (kecontact adapter) in my fork.

**Comment by Apollon77** [comment]
fixed in 2.7.0
