### ISSUE TITLE
Adding support for openknx

### ISSUE THREAD

**Issue by boellner** [ioBroker/ioBroker.discovery#201]
I have implemented a udp search algorithm for knx interfaces.
Please advise how to proceed with my code change.

**Comment by Apollon77** [comment]
Normally you add a class here in this repo which is doing the discovery. For knx Adapter this is kind of there already https://github.com/ioBroker/ioBroker.discovery/blob/master/lib/adapters/knx.js ... so I see two options for openknx:

A) We add a second js file with pot your own discovery logic
B) We enhance the existing one and propose knx AND openknx and then user could decide

**Comment by boellner** [comment]
#203

**Comment by boellner** [comment]
please review the pull request to proceed here

**Comment by Apollon77** [comment]
on my list

**Comment by boellner** [comment]
very good
