### ISSUE TITLE
Adding support for e3dc-rscp

### ISSUE THREAD

**Issue by git-kick** [ioBroker/ioBroker.discovery#205]
I would like to provide discovery for [ioBroker.e3dc-rscp](https://github.com/git-kick/ioBroker.e3dc-rscp), but need some guidance / how-to:
- discovery interface documentation (which functions to implement, parameters, semantics)
- how to test a new `detect()` function in my environment

I verified (using gupnp-tools) that the device is UPnP discoverable (see below).
![grafik](https://user-images.githubusercontent.com/8932938/151825258-5283b3d0-fb89-428a-be0a-a0f535195083.png)
Since e3dc-rscp installations are assumed to remain below 1000, perhaps it's not worth implementing discovery?

**Comment by git-kick** [comment]
Yes, absolutely! I'll give it a try.
Many thanks @Apollon77

**Comment by Apollon77** [comment]
Sure, anytime

**Comment by git-kick** [comment]
e3dc-rscp discovery is running in my test environment.
`e3dc-rscp.js` is quite long, because the adapter needs many polling interval settings for trading off system load vs data timeliness.
[e3dc-rscp.js.txt](https://github.com/ioBroker/ioBroker.discovery/files/7976985/e3dc-rscp.js.txt)

Do you know a good practice to store such amount of default settings in a single source for adapter and discovery? 
With my fresh newbie experience, do you want me to write a brief "quick start" guide to include in the discovery.README?

**Comment by Apollon77** [comment]
it should be enough to just add the relevant fields that have "dynamic data "in this regard and all firldds where you can take the "defaults from io-package.json" can be left out. The system should merge that together

**Comment by git-kick** [comment]
Ah ok, I will drop the "static data" from `e3dc-rscp.js` and then create a PR.
