### ISSUE TITLE
Discovery UI not usable in Admin 3

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.discovery#24]
In Admin3 (3.0.12), discovery 1.1.0:
- buttons are cutted and the normal "Adapter-Konfig"-Buttons are shown together with the Discovery-specific Buttons. Discovery only usable when you know which button is what because not readable
- Progress on search not shown
-result shown but button again cutted.
- vis not installable via discovery (http://forum.iobroker.net/viewtopic.php?p=122031#p122031)

**Comment by AlCalzone** [comment]
Is this still an issue? Seems to work for me atm.

**Comment by foxriver76** [comment]
Works for me too, tested in Firefox.
