### ISSUE TITLE
yeelight support

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.discovery#38]
i already finished with yeelight discovery but i need a different port in the tools.ssdpScan function
https://github.com/ioBroker/ioBroker.discovery/blob/master/lib/tools.js#L361

i need Port 1942 should i integrate it in the tools function (maybe a new value in ip object) or sould i integrate the function in yeelight.js ?

**Comment by Apollon77** [comment]
Make the up as optional Parameter to the scan function ?! What about that?

**Comment by MeisterTR** [comment]
i added the option

**Comment by Apollon77** [comment]
Cool. I check it tomorrow
