### ISSUE TITLE
Discovery adapter crashes when testing for proxmox

### ISSUE THREAD

**Issue by MiSchroe** [ioBroker/ioBroker.discovery#45]
**Describe the bug**
The discovery adapter process crashes during discovery of possible searches. It finds a number of devices and tries to discover the services. The process crashes and restarts. No further progress is shown on the web page.

**To Reproduce**
1. Start a new search in the configuration page of the discovery adapter (Ping is the only selected option)
2. After a while the progress bar doesn't move any more and some errors are logged to the logging (see below)

**Expected behavior**
1. The proxmox supporting library shouldn't crash itself.
2. The discovery adapter shouldn't crash if one of its supporting libraries crashes.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.17134.228], 64bit

**Additional context**
Copy from the log:
````
Source          Time                    Level   Message
discovery.0	2018-09-13 09:45:10.410	info	terminating
discovery.0	2018-09-13 09:45:09.890	error	at Function.Module._load (module.js:438:3)
discovery.0	2018-09-13 09:45:09.890	error	at tryModuleLoad (module.js:446:12)
discovery.0	2018-09-13 09:45:09.890	error	at Module.load (module.js:487:32)
discovery.0	2018-09-13 09:45:09.890	error	at Object.Module._extensions..js (module.js:579:10)
discovery.0	2018-09-13 09:45:09.890	error	at Module._compile (module.js:570:32)
discovery.0	2018-09-13 09:45:09.890	error	at Object.<anonymous> (C:\iobroker_dev\node_modules\iobroker.discovery\lib\adapters\proxmox.js:3:17)
discovery.0	2018-09-13 09:45:09.890	error	at require (internal/module.js:20:19)
discovery.0	2018-09-13 09:45:09.890	error	at Module.require (module.js:497:17)
discovery.0	2018-09-13 09:45:09.890	error	at Function.Module._load (module.js:417:25)
discovery.0	2018-09-13 09:45:09.890	error	at Function.Module._resolveFilename (module.js:469:15)
discovery.0	2018-09-13 09:45:09.890	error	Error: Cannot find module 'request'
discovery.0	2018-09-13 09:45:09.890	error	uncaught exception: Cannot find module 'request'
````

**Comment by Apollon77** [comment]
which nodejs version? Request shopuld only be not available in nodejs 4.x ... starting from 6.x it is included ... o if really nodejs 4.x then I would close here

**Comment by MiSchroe** [comment]
<code>
node --version

v6.11.1
</code>

**Comment by GermanBluefox** [comment]
That should be fixed on gihub yet.
