### ISSUE TITLE
Discovery using broadcast

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.discovery#7]
Some applications / devices can be discovered using UDP broadcasts. This can be achieved for example by mDNS (Apple's Bonjour) or a proprietary protocol (e.g. Logitech Squeezebox Server).

Right now (if I understand the code of this adapter correctly) we are "brute force" testing every adapter on every found IP address.

It would be nice if we could have another category (besides "ip" and "serial") for such adapters. It would be much faster and we wouldn't be bombarding devices on the local network with "unnecessary" TCP requests. My suggestion would be a category "broadcast" that is only called once (similar to "advice").

I can imagine besides my Squeezebox adapter, there could be others that can profit from such a feature.

**Comment by GermanBluefox** [comment]
Adapter uses 3 types of detection: serial, ip and UPnP.
It is listed here:
https://github.com/ioBroker/ioBroker.discovery/tree/master/lib/methods

I thought about the possibility to select discovery methods before
discovery. But it is still ongoing.



2017-04-22 7:53 GMT+02:00 Samuel Weibel <notifications@github.com>:

**Comment by Apollon77** [comment]
The Daikin-adapter uses a combination: it sends a udp packet to the specified IP ... so no reqal general broadcase, but a ip based one. works good too. Check the adapter/daikin.js in discovery

**Comment by Apollon77** [comment]
PS: I also thought and discussued with Bluefox about such a discovery as "method". The "problem" is that you need to discover that broadcast for your adapter. So Daikin is different then others ... so it would be a discovery "per adapter".

If I would more add a "adapter-own-discovery" as method which does nothing, but call a method in the adapter specific code to do the discovery and return a list of ips or even add devices directly.

**Comment by GermanBluefox** [comment]
mDNS is now supported too. Can I close the issue?

**Comment by UncleSamSwiss** [comment]
For the Logitech Squeezebox adapter, it would be nice if I could do a single broadcast myself. Logitech uses a proprietary protocol not compatible with mDNS.

I'll try to code something into the discovery adapter in the next days and then create a pull request. It's probably easier to explain it with some code. We can then discuss the idea in the pull request.

For the idea of Apollon, I see the issue of where the code resides: if you haven't yet installed the adapter, you won't (and shouldn't) be able to run adapter specific code.

**Comment by UncleSamSwiss** [comment]
OK, I'm sorry, it turns out that the discovery protocol for Logitech Squeezebox is actually only for players to find the server. So I had to implement it like any other adapter discovery by checking a TCP port.

I close this issue since it doesn't affect my adapter.
