### ISSUE TITLE
After installing the adapter, system settings open

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.discovery#84]
![image](https://user-images.githubusercontent.com/11523624/79220683-ac4e1980-7e7e-11ea-893b-362f3c50627f.png)

**Comment by Haba1234** [comment]
I have the same problem. When you open a new tab, always first opens discovery

**Comment by Apollon77** [comment]
What’s in the url?

**Comment by instalator** [comment]
![323211111111](https://user-images.githubusercontent.com/11523624/80920164-37dd0b00-8d98-11ea-8325-81fff3e37819.gif)

**Comment by Apollon77** [comment]
In fact this is "as designed "because the "installation wizard" comes as config from this adapter ...
